import 'package:mahareal_flutter_app/pages/consult_page.dart';
import 'package:mahareal_flutter_app/pages/home_page.dart';
import 'package:mahareal_flutter_app/pages/vault_page.dart';

class MyLists {
  MyLists._();

/* Lists */
  static List homePageCategoryLists = [
    allServicesDescList,
    landDocumentsList,
    landServicesList,
    surveysList
  ];

  static const List bottomNavBarRouteList = [
    HomePage(),
    VaultPage(),
    ConsultPage()
  ];

  static const List servicesIconList = [
    "First",
    "Sec",
    "Third",
  ];

/* Services Lists */
  static List allServicesDescList =
      landDocumentsList + landServicesList + surveysList;

  static const List<String> landDocumentsList = [
    "7/12",
    "Index 2",
    "Mutation (Ferfar)",
    "8A",
    "Property Card",
    "Kharedi Khat",
    "Zone Certificate",
  ];

  static const List<String> landServicesList = [
    "Property Search",
    "Apli Chavadi",
    "Bhu Nakasha",
    "Valuation (Jamin Bajar Mulya)",
    "Area Conversions",
    "Measure Land Area",
    "Online Applications",
    "Ferfar Nondani",
    "E-Pik Pahani",
    "Civil Court Case Status",
  ];

  static const List<String> surveysList = [
    "First",
    "Sec",
    "Third",
  ];

/* Services Dropdown Lists */
  static const Map<String, List<String>> servicesDropdownLists = {
    // ToDo: Prepare list of Dropdowns all Services
    "landDocumentsList": landDocumentsList,
    "landServicesList": landServicesList,
    "surveysList": surveysList
  };

// Map < Service Name, List[TextFeilds], List[DropDs], upload enabled? >

  final Map<String, Set<String>> maharashtraDistrictTalukas = {
    'Pune': {
      'Haveli',
      'Mulshi',
      'Mawal',
      'Baramati',
      'Junnar',
      'Daund',
      'Indapur',
      'Shirur',
      'Bhor',
      'Velhe',
      'Ambegaon',
      'Khed',
      'Purandar',
    },
    'Mumbai City': {
      'Mumbai City',
    },
    'Mumbai Suburban': {
      'Andheri',
      'Borivali',
      'Kurla',
    },
    'Thane': {
      'Thane',
      'Kalyan',
      'Ulhasnagar',
      'Bhiwandi',
      'Murbad',
      'Shahapur',
      'Ambarnath',
    },
    'Nashik': {
      'Nashik',
      'Sinnar',
      'Igatpuri',
      'Yeola',
      'Nandgaon',
      'Chandwad',
      'Deola',
      'Malegaon',
      'Dindori',
      'Kalwan',
      'Baglan',
      'Trimbakeshwar',
    },
    'Nagpur': {
      'Nagpur (Rural)',
      'Nagpur (Urban)',
      'Hingna',
      'Umred',
      'Kalameshwar',
      'Katol',
      'Narkhed',
      'Saoner',
      'Ramtek',
      'Bhiwapur',
      'Parseoni',
      'Kuhi',
      'Mauda',
    },
    'Ahmednagar': {
      'Ahmednagar',
      'Shevgaon',
      'Parner',
      'Rahata',
      'Rahuri',
      'Shrirampur',
      'Kopargaon',
      'Pathardi',
      'Sangamner',
      'Shrigonda',
      'Nevasa',
      'Jamkhed',
      'Akole',
    },
    'Solapur': {
      'Solapur North',
      'Solapur South',
      'Barshi',
      'Pandharpur',
      'Sangola',
      'Akkalkot',
      'Mangalwedha',
      'Madha',
      'Karmala',
      'Malshiras',
    },
    'Kolhapur': {
      'Karvir',
      'Hatkanangale',
      'Shirol',
      'Panhala',
      'Shahuwadi',
      'Gaganbavda',
      'Radhanagari',
      'Kagal',
      'Ajra',
      'Chandgad',
      'Gadhinglaj',
    },
    'Satara': {
      'Satara',
      'Karad',
      'Phaltan',
      'Koregaon',
      'Wai',
      'Khatav',
      'Jaoli',
      'Mahabaleshwar',
      'Man',
      'Patan',
    },
    'Aurangabad': {
      'Aurangabad',
      'Kannad',
      'Sillod',
      'Gangapur',
      'Vaijapur',
      'Paithan',
      'Soyagaon',
      'Khuldabad',
    },
    'Beed': {
      'Beed',
      'Ashti',
      'Patoda',
      'Georai',
      'Ambajogai',
      'Kaij',
      'Parli',
      'Wadwani',
    },
    'Latur': {
      'Latur',
      'Ausa',
      'Nilanga',
      'Renapur',
      'Udgir',
      'Ahmedpur',
      'Jalkot',
      'Chakur',
      'Shirur Anantpal',
    },
    'Amravati': {
      'Amravati',
      'Achalpur',
      'Morshi',
      'Chandur Bazar',
      'Daryapur',
      'Warud',
      'Chikhaldara',
      'Nandgaon-Khandeshwar',
      'Dhamangaon Railway',
      'Teosa',
      'Anjangaon Surji',
      'Bhatkuli',
    },
    'Yavatmal': {
      'Yavatmal',
      'Wani',
      'Pusad',
      'Ghatanji',
      'Kelapur',
      'Mahagaon',
      'Arni',
      'Digras',
      'Darwha',
      'Ner',
      'Umarkhed',
    },
    'Bhandara': {
      'Bhandara',
      'Tumsar',
      'Sakoli',
      'Mohadi',
      'Pauni',
      'Lakhandur',
      'Lakhani',
    },
    'Gondia': {
      'Gondia',
      'Tirora',
      'Deori',
      'Amgaon',
      'Arjuni Morgaon',
      'Salekasa',
      'Goregaon',
    },
    'Chandrapur': {
      'Chandrapur',
      'Ballarpur',
      'Rajura',
      'Bhadravati',
      'Warora',
      'Brahmapuri',
      'Mul',
      'Pombhurna',
      'Nagbhid',
      'Chimur',
      'Korpana',
      'Saoli',
    },
    'Wardha': {
      'Wardha',
      'Hinganghat',
      'Deoli',
      'Seloo',
      'Arvi',
      'Ashti',
      'Karanja',
      'Samudrapur',
    },
    'Jalgaon': {
      'Jalgaon',
      'Bhusawal',
      'Chopda',
      'Erandol',
      'Yawal',
      'Raver',
      'Jamner',
      'Pachora',
      'Amalner',
      'Bodwad',
      'Parola',
      'Dharangaon',
    },
    'Nandurbar': {
      'Nandurbar',
      'Akkalkuwa',
      'Shahada',
      'Talasari',
      'Navapur',
      'Dhadgaon',
    },
    'Dhule': {
      'Dhule',
      'Shirpur',
      'Sakri',
      'Sindkheda',
    },
    'Parbhani': {
      'Parbhani',
      'Pathri',
      'Jintur',
      'Manwath',
      'Sonpeth',
      'Purna',
      'Selu',
      'Palam',
      'Gangakhed',
    },
    'Hingoli': {
      'Hingoli',
      'Kalamnuri',
      'Sengaon',
      'Aundha Nagnath',
      'Basmath',
    },
    'Nanded': {
      'Nanded',
      'Deglur',
      'Mukhed',
      'Kandhar',
      'Hadgaon',
      'Loha',
      'Naigaon',
      'Kinwat',
      'Bhokar',
      'Ardhapur',
      'Umri',
    },
    'Osmanabad': {
      'Osmanabad',
      'Tuljapur',
      'Omerga',
      'Kalamb',
      'Paranda',
      'Bhoom',
      'Washi',
    },
    'Ratnagiri': {
      'Ratnagiri',
      'Chiplun',
      'Guhagar',
      'Lanja',
      'Dapoli',
      'Sangameshwar',
      'Rajapur',
      'Mandangad',
    },
    'Sindhudurg': {
      'Kankavli',
      'Kudal',
      'Sawantwadi',
      'Vengurla',
      'Dodamarg',
      'Malvan',
      'Devgad',
      'Vaibhavwadi',
    },
    'Palghar': {
      'Palghar',
      'Dahanu',
      'Vasai',
      'Vikramgad',
      'Talasari',
      'Jawhar',
      'Wada',
      'Mokhada',
    },
  };
}
